version: 0.2
env:
  shell: bash
#  variables:
#    TEMPLATE_BUCKET: "amx-app-de-s3-managed-stack"
#    TEMPLATE_FILE: "AMX-RXS-EKS-TSK-1-CF.yaml"
#    PARAMETER_FILE: "AMX-RXS-EKS-TSK-1-CF.json"
#    STACK_NAME: "AMX-RXS-EKS-TSK-1-CF"

phases:
  pre_build:
    commands:
      - aws cloudformation describe-stacks --stack-name ${StackName} --query 'Stacks[0].Parameters' | jq '[ .[] | select(.ParameterKey) ]' > /tmp/${StackName}.json
      - aws cloudformation list-exports --query 'Exports' > /tmp/Exports.json
#     Parameters
      - AppPrefix=$(cat /tmp/${StackName}.json | jq '.[] | select(.ParameterKey == "AppPrefix") | .ParameterValue' | tr -d '"')
      - StackEnvironment=$(cat /tmp/${StackName}.json | jq '.[] | select(.ParameterKey == "StackEnvironment") | .ParameterValue' | tr -d '"')
      - TemplateFileName=$(cat /tmp/${StackName}.json | jq '.[] | select(.ParameterKey == "TemplateFileName") | .ParameterValue' | tr -d '"')
      - ParameterFileName=$(cat /tmp/${StackName}.json | jq '.[] | select(.ParameterKey == "ParameterFileName") | .ParameterValue' | tr -d '"')
      - NewStackName=$(cat /tmp/${StackName}.json | jq '.[] | select(.ParameterKey == "NewStackName") | .ParameterValue' | tr -d '"')
      - CodePipelineName=$(cat /tmp/${StackName}.json | jq '.[] | select(.ParameterKey == "CodePipelineName") | .ParameterValue' | tr -d '"')
      - IaCBucketName=$(cat /tmp/${StackName}.json | jq '.[] | select(.ParameterKey == "IaCBucketName") | .ParameterValue' | tr -d '"')
#     Exports
#      - ExportName="${AppPrefix,,}-${StackEnvironment,,}-nested-bucket-name-${CodePipelineName}"
#      - NestedBucketName=$(cat /tmp/Exports.json | jq '.[] | select(.Name == "'${ExportName}'") | .Value' | tr -d '"')
      - |
        STACK_NAME=$(aws cloudformation describe-stacks                               \
                       --query 'Stacks[?StackName==`'${NewStackName}'`].StackName'    \
                       --output text)
      - echo ${STACK_NAME}
      - |
        if [ "${STACK_NAME}" == "" ]
        then
          ChangeSetType="CREATE"
        else
          ChangeSetType="UPDATE"
        fi
      - echo $ChangeSetType
      - ChangeSetName=${AppPrefix,,}-${StackEnvironment,,}-change-set-${CodePipelineName}-$(date +%s)
  build:
    commands:
      - env
      - echo "Create Change Set"
      - cd $CODEBUILD_SRC_DIR_SourceIaC/
      - ls -lR
      - |
        aws cloudformation create-change-set                  \
          --stack-name ${NewStackName}                        \
          --change-set-name ${ChangeSetName}                  \
          --template-url https://${IaCBucketName}.s3.amazonaws.com/${TemplateFileName} \
          --parameters file://${ParameterFileName}            \
          --capabilities CAPABILITY_NAMED_IAM                 \
          --include-nested-stacks                             \
          --change-set-type ${ChangeSetType}
      - |
        aws cloudformation wait change-set-create-complete   \
          --stack-name ${NewStackName}                       \
          --change-set-name ${ChangeSetName}
      - |
        aws cloudformation describe-change-set                \
          --stack-name ${NewStackName}                        \
          --change-set-name ${ChangeSetName}
      - echo ${ChangeSetName} > /tmp/ChangeSetName.txt

artifacts:
  files:
    - /tmp/ChangeSetName.txt
